# Task 1

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os


In [2]:
#defining a path
path=r'C:\Users\banda\Instacart Basket Analysis'

In [3]:
# importing customer data
Cust_df = pd.read_csv(os.path.join(path, '02 Data', 'Original data', 'customers.csv'), index_col=False)

In [4]:
Cust_df.head()

user_id First Name    Surnam  Gender       STATE  Age date_joined  \
0    26711    Deborah  Esquivel  Female    Missouri   48    1/1/2017   
1    33890   Patricia      Hart  Female  New Mexico   36    1/1/2017   
2    65803    Kenneth    Farley    Male       Idaho   35    1/1/2017   
3   125935   Michelle     Hicks  Female        Iowa   40    1/1/2017   
4   130797        Ann   Gilmore  Female    Maryland   26    1/1/2017   

   n_dependants fam_status  income  
0             3    married  165665  
1             0     single   59285  
2             2    married   99568  
3             0     single   42049  
4             1    married   40374

In [5]:
Cust_df.shape

(206209, 10)

In [6]:
Cust_df.describe()

user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In [7]:
#checking data types
Cust_df.dtypes

user_id          int64
First Name      object
Surnam          object
Gender          object
STATE           object
Age              int64
date_joined     object
n_dependants     int64
fam_status      object
income           int64
dtype: object

In [8]:
Cust_df.isnull().sum()

user_id             0
First Name      11259
Surnam              0
Gender              0
STATE               0
Age                 0
date_joined         0
n_dependants        0
fam_status          0
income              0
dtype: int64

### Renaming 

In [9]:
Cust_df.rename(columns = {'First Name' : 'First_name'}, inplace = True) 

In [10]:
Cust_df.rename(columns = {'Surnam' : 'Last_name'}, inplace = True) 

In [11]:
Cust_df.rename(columns = {'STATE' : 'State'}, inplace = True) 

In [12]:
Cust_df.rename(columns = {'n_dependants' : 'Number_of_dependants'}, inplace = True) 

In [13]:
Cust_df.rename(columns = {'fam_status' : 'Family_status'}, inplace = True) 

In [14]:
Cust_df.head()

user_id First_name Last_name  Gender       State  Age date_joined  \
0    26711    Deborah  Esquivel  Female    Missouri   48    1/1/2017   
1    33890   Patricia      Hart  Female  New Mexico   36    1/1/2017   
2    65803    Kenneth    Farley    Male       Idaho   35    1/1/2017   
3   125935   Michelle     Hicks  Female        Iowa   40    1/1/2017   
4   130797        Ann   Gilmore  Female    Maryland   26    1/1/2017   

   Number_of_dependants Family_status  income  
0                     3       married  165665  
1                     0        single   59285  
2                     2       married   99568  
3                     0        single   42049  
4                     1       married   40374

In [15]:
Cust_df.rename(columns = {'Marital_status':'Family_status'}, inplace = True)

In [16]:
Cust_df.head()

user_id First_name Last_name  Gender       State  Age date_joined  \
0    26711    Deborah  Esquivel  Female    Missouri   48    1/1/2017   
1    33890   Patricia      Hart  Female  New Mexico   36    1/1/2017   
2    65803    Kenneth    Farley    Male       Idaho   35    1/1/2017   
3   125935   Michelle     Hicks  Female        Iowa   40    1/1/2017   
4   130797        Ann   Gilmore  Female    Maryland   26    1/1/2017   

   Number_of_dependants Family_status  income  
0                     3       married  165665  
1                     0        single   59285  
2                     2       married   99568  
3                     0        single   42049  
4                     1       married   40374

### Change data type to save space and categorical variable to string: Wrangle the data 

In [17]:
Cust_df['user_id'].dtype

dtype('int64')

In [18]:
#changing data type integer to string
Cust_df['user_id'] = Cust_df['user_id'].astype('str')

In [19]:
#checking result
Cust_df['user_id'].dtype

dtype('O')

In [20]:
Cust_df['Age'].dtype

dtype('int64')

In [21]:
#changing int size from 64 to 8 to save space
Cust_df['Age'] = Cust_df['Age'].astype('int8')

In [22]:
#checking result
Cust_df['Age'].dtype

dtype('int8')

In [23]:
#changing int size from 64 to 8 to save space
Cust_df['Number_of_dependants'] = Cust_df['Number_of_dependants'].astype('int8')

In [24]:
#checking result
Cust_df['Number_of_dependants'].dtype

dtype('int8')

In [25]:
#changing int size from 64 to 32 to save space
Cust_df['income'] = Cust_df['income'].astype('int32')

In [26]:
#checking result
Cust_df['income'].dtype

dtype('int32')

###  Data Consistency Checks

In [27]:
# checking for missing values
Cust_df.isnull().sum()

user_id                     0
First_name              11259
Last_name                   0
Gender                      0
State                       0
Age                         0
date_joined                 0
Number_of_dependants        0
Family_status               0
income                      0
dtype: int64

In [28]:
#creating new subset that contains only duplicated
cust_dups = Cust_df[Cust_df.duplicated()]

In [29]:
#no duplicate value found in customer data
cust_dups

Empty DataFrame
Columns: [user_id, First_name, Last_name, Gender, State, Age, date_joined, Number_of_dependants, Family_status, income]
Index: []

In [30]:
#checking for mix datatypes
for col in Cust_df.columns.tolist():
    weird = (Cust_df[[col]].map(type) != Cust_df[[col]].iloc[0].apply(type)).any(axis = 1)
    
    if len (Cust_df[weird]) > 0:
        print (col)

First_name


In [31]:
Cust_df['First_name'].head()

0     Deborah
1    Patricia
2     Kenneth
3    Michelle
4         Ann
Name: First_name, dtype: object

In [32]:
#changing mix datatype to string value
Cust_df['First_name'] = Cust_df['First_name'].astype('str')

In [33]:
Cust_df.isnull().sum()

user_id                 0
First_name              0
Last_name               0
Gender                  0
State                   0
Age                     0
date_joined             0
Number_of_dependants    0
Family_status           0
income                  0
dtype: int64

since the first_name datype change to string shows no null value.

In [34]:
Cust_df['Gender'].value_counts(dropna=False)

Gender
Male      104067
Female    102142
Name: count, dtype: int64

2 gender typed and seem to be not much difference on those 2

In [35]:
#checking for unique states
Cust_df['State'].nunique()

51

In [36]:
Cust_df['State'].value_counts(dropna=False)

State
Florida                 4044
Colorado                4044
Illinois                4044
Alabama                 4044
District of Columbia    4044
Hawaii                  4044
Arizona                 4044
Connecticut             4044
California              4044
Indiana                 4044
Arkansas                4044
Alaska                  4044
Delaware                4044
Iowa                    4044
Idaho                   4044
Georgia                 4044
Wyoming                 4043
Mississippi             4043
Oklahoma                4043
Utah                    4043
New Hampshire           4043
Kentucky                4043
Maryland                4043
Rhode Island            4043
Massachusetts           4043
Michigan                4043
New Jersey              4043
Kansas                  4043
South Dakota            4043
Minnesota               4043
Tennessee               4043
New York                4043
Washington              4043
Louisiana               4043
Montana 

51 sates instead of 50 where DC is stated as state, customers are equally divided across the states.

In [37]:
Cust_df['Family_status'].value_counts(dropna=False)

Family_status
married                             144906
single                               33962
divorced/widowed                     17640
living with parents and siblings      9701
Name: count, dtype: int64

high number of married status than single and so on

In [38]:
Cust_df['Number_of_dependants'].value_counts(dropna=False)

Number_of_dependants
0    51602
3    51594
1    51531
2    51482
Name: count, dtype: int64

In [39]:
Cust_df['income'].value_counts(dropna=False)

income
57192     10
95891     10
95710     10
97532      9
98675      9
          ..
73141      1
71524      1
74408      1
44780      1
148828     1
Name: count, Length: 108012, dtype: int64

In [40]:
Cust_df['Age'].describe()

count    206209.000000
mean         49.501646
std          18.480962
min          18.000000
25%          33.000000
50%          49.000000
75%          66.000000
max          81.000000
Name: Age, dtype: float64

Average age seems to be around 49 of age, min of 18 yrs old and the oldest population are at 81 yrs old

In [41]:
Cust_df['income'].describe()

count    206209.000000
mean      94632.852548
std       42473.786988
min       25903.000000
25%       59874.000000
50%       93547.000000
75%      124244.000000
max      593901.000000
Name: income, dtype: float64

Mean income at 94632, max 593901 and min of 25903

In [42]:
Cust_df['income'].median()

93547.0

In [ ]:
#changing data type of date_joined to pd datetime
Cust_df['date_joined'] = pd.to_datetime(Cust_df['date_joined'])


In [75]:
Cust_df['date_joined'].min()

Timestamp('2017-01-01 00:00:00')

In [76]:
Cust_df['date_joined'].max()

Timestamp('2020-04-01 00:00:00')

Date joined from Jan 2017 to jan 2020

In [46]:
Cust_df.to_pickle(os.path.join(path,'02 Data','Prepared data','Cust_df_wrangle.pkl'))

### Combining Ords_prods and Customer data

Importing Ords_prods

In [47]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data','Prepared data','ords_prods_merge_2.pkl'))

In [48]:
ords_prods_merge.head()

order_id  user_id  order_number  orders_day_of_week  order_hour_of_day  \
0   2539329        1             1                   2                  8   
1   2398795        1             2                   3                  7   
2    473747        1             3                   3                 12   
3   2254736        1             4                   4                  7   
4    431534        1             5                   4                 15   

   days_since_prior_order  product_id  add_to_cart_order  reordered  \
0                    20.0         196                  1          0   
1                    15.0         196                  1          1   
2                    21.0         196                  1          1   
3                    29.0         196                  1          1   
4                    28.0         196                  1          1   

  product_name  ...  _merge    price_range_loc  busiest_period_of_day  \
0         Soda  ...    both  Mid-range product         Average orders   
1         Soda  ...    both  Mid-range product         Average orders   
2         Soda  ...    both  Mid-range product         Average orders   
3         Soda  ...    both  Mid-range product         Average orders   
4         Soda  ...    both  Mid-range product         Average orders   

     busiest_days max_order  loyalty_flag mean_buyer  Spending_flag  \
0  Regularly days        10  New customer   6.367797    Low spender   
1    Slowest days        10  New customer   6.367797    Low spender   
2    Slowest days        10  New customer   6.367797    Low spender   
3    Slowest days        10  New customer   6.367797    Low spender   
4    Slowest days        10  New customer   6.367797    Low spender   

  median_ordering   Order_frequency_flag  
0            20.5  Non-frequent customer  
1            20.5  Non-frequent customer  
2            20.5  Non-frequent customer  
3            20.5  Non-frequent customer  
4            20.5  Non-frequent customer  

[5 rows x 23 columns]

In [49]:
ords_prods_merge.shape

(32404859, 23)

In [50]:
ords_prods_merge.dtypes

order_id                     int64
user_id                      int64
order_number                 int64
orders_day_of_week           int64
order_hour_of_day            int64
days_since_prior_order     float64
product_id                   int64
add_to_cart_order            int64
reordered                    int64
product_name                object
aisle_id                     int64
department_id                int64
prices                     float64
_merge                    category
price_range_loc             object
busiest_period_of_day       object
busiest_days                object
max_order                    int64
loyalty_flag                object
mean_buyer                 float64
Spending_flag               object
median_ordering            float64
Order_frequency_flag        object
dtype: object

In [51]:
Cust_df.dtypes

user_id                         object
First_name                      object
Last_name                       object
Gender                          object
State                           object
Age                               int8
date_joined             datetime64[ns]
Number_of_dependants              int8
Family_status                   object
income                           int32
dtype: object

In [52]:
ords_prods_merge['user_id'] = ords_prods_merge['user_id'].astype('str')

In [53]:
ords_prods_merge['order_id'] = ords_prods_merge['order_id'].astype('str')

In [54]:
ords_prods_merge['order_number'] = ords_prods_merge['order_number'].astype('int32')

In [55]:
ords_prods_merge['orders_day_of_week'] = ords_prods_merge['orders_day_of_week'].astype('int8')

In [56]:
ords_prods_merge['order_hour_of_day'] = ords_prods_merge['order_hour_of_day'].astype('int8')

In [57]:
ords_prods_merge['add_to_cart_order'] = ords_prods_merge['add_to_cart_order'].astype('int32')

In [58]:
ords_prods_merge['product_id'] = ords_prods_merge['product_id'].astype('object')

In [59]:
ords_prods_merge['reordered'] = ords_prods_merge['reordered'].astype('int32')

In [60]:
ords_prods_merge['aisle_id'] = ords_prods_merge['aisle_id'].astype('int8')

In [61]:
ords_prods_merge['department_id'] = ords_prods_merge['department_id'].astype('int32')

In [62]:
ords_prods_merge['max_order'] = ords_prods_merge['max_order'].astype('int8')

In [63]:
ords_prods_merge['user_id'].dtypes

dtype('O')

In [64]:
ords_prods_merge.dtypes

order_id                    object
user_id                     object
order_number                 int32
orders_day_of_week            int8
order_hour_of_day             int8
days_since_prior_order     float64
product_id                  object
add_to_cart_order            int32
reordered                    int32
product_name                object
aisle_id                      int8
department_id                int32
prices                     float64
_merge                    category
price_range_loc             object
busiest_period_of_day       object
busiest_days                object
max_order                     int8
loyalty_flag                object
mean_buyer                 float64
Spending_flag               object
median_ordering            float64
Order_frequency_flag        object
dtype: object

In [65]:
#had to drop _merge colummn because it ws effecting the merge
ords_prods_merge.drop(columns=['_merge'], inplace=True)

In [66]:
ords_prods_merge.head()

order_id user_id  order_number  orders_day_of_week  order_hour_of_day  \
0  2539329       1             1                   2                  8   
1  2398795       1             2                   3                  7   
2   473747       1             3                   3                 12   
3  2254736       1             4                   4                  7   
4   431534       1             5                   4                 15   

   days_since_prior_order product_id  add_to_cart_order  reordered  \
0                    20.0        196                  1          0   
1                    15.0        196                  1          1   
2                    21.0        196                  1          1   
3                    29.0        196                  1          1   
4                    28.0        196                  1          1   

  product_name  ...  prices    price_range_loc  busiest_period_of_day  \
0         Soda  ...     9.0  Mid-range product         Average orders   
1         Soda  ...     9.0  Mid-range product         Average orders   
2         Soda  ...     9.0  Mid-range product         Average orders   
3         Soda  ...     9.0  Mid-range product         Average orders   
4         Soda  ...     9.0  Mid-range product         Average orders   

     busiest_days max_order  loyalty_flag  mean_buyer Spending_flag  \
0  Regularly days        10  New customer    6.367797   Low spender   
1    Slowest days        10  New customer    6.367797   Low spender   
2    Slowest days        10  New customer    6.367797   Low spender   
3    Slowest days        10  New customer    6.367797   Low spender   
4    Slowest days        10  New customer    6.367797   Low spender   

   median_ordering   Order_frequency_flag  
0             20.5  Non-frequent customer  
1             20.5  Non-frequent customer  
2             20.5  Non-frequent customer  
3             20.5  Non-frequent customer  
4             20.5  Non-frequent customer  

[5 rows x 22 columns]

In [67]:
#merging cust_df to ords_prods_merge data
ords_prods_cust_dfmerge = ords_prods_merge.merge(Cust_df, on=['user_id'], indicator=True)

In [68]:
ords_prods_cust_dfmerge.head()

order_id user_id  order_number  orders_day_of_week  order_hour_of_day  \
0  2539329       1             1                   2                  8   
1  2398795       1             2                   3                  7   
2   473747       1             3                   3                 12   
3  2254736       1             4                   4                  7   
4   431534       1             5                   4                 15   

   days_since_prior_order product_id  add_to_cart_order  reordered  \
0                    20.0        196                  1          0   
1                    15.0        196                  1          1   
2                    21.0        196                  1          1   
3                    29.0        196                  1          1   
4                    28.0        196                  1          1   

  product_name  ...  First_name  Last_name  Gender    State Age date_joined  \
0         Soda  ...       Linda     Nguyen  Female  Alabama  31  2019-02-17   
1         Soda  ...       Linda     Nguyen  Female  Alabama  31  2019-02-17   
2         Soda  ...       Linda     Nguyen  Female  Alabama  31  2019-02-17   
3         Soda  ...       Linda     Nguyen  Female  Alabama  31  2019-02-17   
4         Soda  ...       Linda     Nguyen  Female  Alabama  31  2019-02-17   

   Number_of_dependants Family_status  income _merge  
0                     3       married   40423   both  
1                     3       married   40423   both  
2                     3       married   40423   both  
3                     3       married   40423   both  
4                     3       married   40423   both  

[5 rows x 32 columns]

In [69]:
ords_prods_cust_dfmerge.shape

(32404859, 32)

In [70]:
ords_prods_cust_dfmerge['_merge'].value_counts(dropna=False)

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [71]:
ords_prods_cust_dfmerge.drop(columns=['_merge'], inplace=True)

In [72]:
ords_prods_cust_dfmerge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 31 columns):
 #   Column                  Dtype         
---  ------                  -----         
 0   order_id                object        
 1   user_id                 object        
 2   order_number            int32         
 3   orders_day_of_week      int8          
 4   order_hour_of_day       int8          
 5   days_since_prior_order  float64       
 6   product_id              object        
 7   add_to_cart_order       int32         
 8   reordered               int32         
 9   product_name            object        
 10  aisle_id                int8          
 11  department_id           int32         
 12  prices                  float64       
 13  price_range_loc         object        
 14  busiest_period_of_day   object        
 15  busiest_days            object        
 16  max_order               int8          
 17  loyalty_flag            object        
 18  

## Exporting data to pickle file

In [73]:
ords_prods_cust_dfmerge.to_pickle(os.path.join(path, '02 Data','Prepared Data','ords_prods_cust_dfmerge.pkl'))